language: ruby
rvm:
- 2.2.3
script:
- bin/rake test
notifications:
  slack:
    secure: Tia5Q61EjvqFZjwpJD0QnzFWzR7stnyn6CoMFQPHKXdzD81lwCoDI1balZpoYhTSmR2nC+yJ10aMMI69DEuiAa8dZXMtfZdTVo6G/98o1PDlw/8BgAeVJbq/W7lUcSzShRsHtkF9VSOLz0gipHTpNDgUWnIPMICXgZqe0GzXrpHJBv2Uplq9Atj8j4tMUl9UYP3QN0vu4t6qDP39geJv+L311d7/MX0TJdeRMP0pO6kubIJoR7sFyc6b4lzRv6cg1EY3B3tv59oZpvlHkTj1I5Nh6kGMRtNVwOI4NRfO408UyiVHP4AuaEk4MsJpo+3PnQVb6LrN9tD7l5IcuOuoZ8hGMnRXqhz9B+QU5jdKVp7QtZEDbN9Lqf3umG1euKwZMXkuSPStcy1rohlLvXCRM9nd4P78TaDIuxWnalPQmNxSskSb3nBTRV90Y8bBzsGnj/Wix5cHJDLXeFOENaPO09L32pYZMU9pHmPPya5ZFQfB2aXcGZb/LhCLSb3EGbblFfjvouPUuXivpLgiE64rNNZjXStDKbNzYxr+eLkgzJPvpMbR7T5gT7fUizk5ECmj1y/8yw2ZJftA0YaDKbqb0iFJmrcdMCJczpxequ0HSKIlbMUVVT6Yipxla/+F62033JTeBpvutxUeuiQO6Arfbh8fmyEpuxaWOhXwelAWLWI=
